// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Api.Data;

#nullable disable

namespace WebApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708073916_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Api.Models.ExecutionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilityId");

                    b.ToTable("ExecutionResults");
                });

            modelBuilder.Entity("WebApp.Api.Models.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsImplemented")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Числа",
                            Description = "Суммирует числа, переданные по одному на строку.",
                            Difficulty = 1,
                            Endpoint = "sum-numbers",
                            IsImplemented = true,
                            Name = "Сумма чисел"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Текст",
                            Description = "Заменяет несколько подстрок одновременно по словарю замен.",
                            Difficulty = 2,
                            Endpoint = "multi-replace",
                            IsImplemented = false,
                            Name = "Множественная замена в тексте"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Данные",
                            Description = "Преобразует CSV-данные в SQL-скрипт для создания временной таблицы и вставки строк.",
                            Difficulty = 2,
                            Endpoint = "csv-to-sql",
                            IsImplemented = false,
                            Name = "CSV в SQL INSERT"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Код",
                            Description = "Преобразует строки (по одной на линию) в переменную-список на C# или JavaScript.",
                            Difficulty = 1,
                            Endpoint = "text-to-list",
                            IsImplemented = false,
                            Name = "Текст в список C# / JS"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Безопасность",
                            Description = "Генерирует надёжный пароль заданной длины с выбором наборов символов.",
                            Difficulty = 1,
                            Endpoint = "password-gen",
                            IsImplemented = false,
                            Name = "Генератор паролей"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Текст",
                            Description = "Считает символы, слова, строки и предложения в тексте.",
                            Difficulty = 1,
                            Endpoint = "text-stats",
                            IsImplemented = false,
                            Name = "Подсчёт символов / слов"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Текст",
                            Description = "Преобразует текст в UPPER, lower, Title Case, camelCase, snake_case.",
                            Difficulty = 2,
                            Endpoint = "case-converter",
                            IsImplemented = false,
                            Name = "Конвертер регистров"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Кодирование",
                            Description = "Кодирует и декодирует строки в формат Base64.",
                            Difficulty = 1,
                            Endpoint = "base64",
                            IsImplemented = false,
                            Name = "Base64 кодер / декодер"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Данные",
                            Description = "Форматирует (pretty-print) или минифицирует JSON-строку.",
                            Difficulty = 2,
                            Endpoint = "json-formatter",
                            IsImplemented = false,
                            Name = "JSON-форматировщик"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Безопасность",
                            Description = "Вычисляет MD5 / SHA1 / SHA256 хеш переданной строки.",
                            Difficulty = 1,
                            Endpoint = "hash-calc",
                            IsImplemented = false,
                            Name = "Хеш-калькулятор"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Код",
                            Description = "Генерирует один или несколько UUID и копирует в буфер обмена.",
                            Difficulty = 1,
                            Endpoint = "uuid-gen",
                            IsImplemented = false,
                            Name = "Генератор UUID / GUID"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Текст",
                            Description = "Сортирует строки по алфавиту, длине, в обратном порядке, с удалением дубликатов.",
                            Difficulty = 1,
                            Endpoint = "string-sort",
                            IsImplemented = false,
                            Name = "Сортировщик строк"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Дата и время",
                            Description = "Вычисляет разницу между датами, добавляет дни / месяцы / годы к дате.",
                            Difficulty = 2,
                            Endpoint = "date-calc",
                            IsImplemented = false,
                            Name = "Калькулятор дат"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Числа",
                            Description = "Переводит числа между DEC, HEX, BIN, OCT с произвольной точностью.",
                            Difficulty = 2,
                            Endpoint = "number-base",
                            IsImplemented = false,
                            Name = "Конвертер чисел (системы счисления)"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Кодирование",
                            Description = "Экранирует / деэкранирует строки для HTML, JSON, SQL, URL.",
                            Difficulty = 2,
                            Endpoint = "string-escape",
                            IsImplemented = false,
                            Name = "Экранирование строк"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Текст",
                            Description = "Генерирует заданное число абзацев / слов / символов текста-рыбы.",
                            Difficulty = 1,
                            Endpoint = "lorem-ipsum",
                            IsImplemented = false,
                            Name = "Генератор Lorem Ipsum"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Данные",
                            Description = "Проверяет корректность структуры и форматирует с отступами.",
                            Difficulty = 3,
                            Endpoint = "yaml-json",
                            IsImplemented = false,
                            Name = "Валидатор и форматировщик JSON / YAML"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Данные",
                            Description = "Конвертирует CSV в массив JSON-объектов и обратно.",
                            Difficulty = 2,
                            Endpoint = "csv-json",
                            IsImplemented = false,
                            Name = "Преобразователь CSV ↔ JSON"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Код",
                            Description = "Помогает составить и протестировать регулярное выражение на тестовых строках.",
                            Difficulty = 3,
                            Endpoint = "regex-tester",
                            IsImplemented = false,
                            Name = "Построитель регулярных выражений"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Дата и время",
                            Description = "Конвертирует Unix timestamp в читаемую дату и обратно.",
                            Difficulty = 1,
                            Endpoint = "unix-time",
                            IsImplemented = false,
                            Name = "Unix Timestamp конвертер"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Безопасность",
                            Description = "Декодирует JWT-токен, показывает Header/Payload в читаемом виде, подсвечивает истекшие токены, генерирует тестовые JWT.",
                            Difficulty = 2,
                            Endpoint = "jwt-debugger",
                            IsImplemented = false,
                            Name = "JWT Decoder & Debugger"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Текст",
                            Description = "Показывает ASCII/Unicode-коды каждого символа текста и собирает строку из кодов обратно. Помогает найти невидимые символы.",
                            Difficulty = 1,
                            Endpoint = "char-inspector",
                            IsImplemented = false,
                            Name = "Инспектор символов (ASCII/Unicode)"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Кодирование",
                            Description = "Кодирует/декодирует URL-строки, парсит query-параметры в таблицу ключ-значение с авто-декодированием и генерирует JSON-объект.",
                            Difficulty = 2,
                            Endpoint = "url-tools",
                            IsImplemented = false,
                            Name = "URL Encoder / Decoder + Query Parser"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Дизайн",
                            Description = "Конвертирует цвета между HEX, RGB, HSL, CMYK. Определяет контрастные пары, проверяет на доступность (color-blindness).",
                            Difficulty = 2,
                            Endpoint = "color-converter",
                            IsImplemented = false,
                            Name = "Конвертер цветов"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Код",
                            Description = "Форматирует SQL-запросы с отступами (beautify) или сжимает в одну строку (minify).",
                            Difficulty = 2,
                            Endpoint = "sql-formatter",
                            IsImplemented = false,
                            Name = "SQL Formatter / Minifier"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Текст",
                            Description = "Сравнивает два блока текста и подсвечивает добавленные, удалённые и изменённые строки.",
                            Difficulty = 2,
                            Endpoint = "text-diff",
                            IsImplemented = false,
                            Name = "Текстовый Diff-инструмент"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Числа",
                            Description = "Вычисляет: «X это Y% от чего?», «На сколько % изменилось от A до B?», пропорциональное масштабирование.",
                            Difficulty = 1,
                            Endpoint = "percent-calc",
                            IsImplemented = false,
                            Name = "Калькулятор пропорций и процентов"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Текст",
                            Description = "Шифрование текста",
                            Difficulty = 2,
                            Endpoint = "cipher-text",
                            IsImplemented = true,
                            Name = "Шифрование текста"
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.ExecutionResult", b =>
                {
                    b.HasOne("WebApp.Api.Models.Utility", "Utility")
                        .WithMany()
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utility");
                });
#pragma warning restore 612, 618
        }
    }
}
